# Generated by Django 4.2.2 on 2023-06-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("get_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_type_code", models.CharField(max_length=255)),
                ("record_num", models.IntegerField()),
                ("created_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField()),
            ],
        ),
    ]
